import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * DEPLOY TARGET — GitHub Pages on the custom domain kalapritidesigns.com.
 *
 * Because the site is served from the domain apex rather than a repository
 * subpath, the base is "/". It is read from VITE_BASE so a one-off preview
 * build can still be produced for stackified.github.io/kalapriti/ without
 * editing this file — hardcoding the base is what broke this site twice.
 *
 * Every asset URL comes from `asset()` in src/data/site.js, which reads
 * import.meta.env.BASE_URL. Vite rewrites the favicon inside index.html
 * automatically, so nothing there needs touching either.
 */
const BASE = process.env.VITE_BASE || '/'

/**
 * GitHub Pages performs no server-side rewrites, so a deep link such as
 * /services is answered with 404.html. That file encodes the requested path
 * into a query string and bounces to index.html, where a snippet restores the
 * real URL before React mounts.
 *
 * `pathSegmentsToKeep` must equal the number of path segments in the base — 0
 * on the apex domain, 1 under /kalapriti/. Generating the file here rather than
 * keeping a static copy in public/ means the two can never drift apart.
 */
function ghPagesSpaFallback(base) {
  const segments = base.split('/').filter(Boolean).length
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Kalapriti Designs</title>
    <script>
      // GENERATED by vite.config.js — do not edit by hand.
      var pathSegmentsToKeep = ${segments}
      var l = window.location
      l.replace(
        l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
        l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
        l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
        (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
        l.hash
      )
    </script>
  </head>
  <body></body>
</html>
`
}

/**
 * Per-route pages, the sitemap, robots.txt and llms.txt are written after both
 * builds by scripts/prerender.mjs, which needs the SSR bundle to render page
 * content. This plugin only owns the 404 shim, because that depends on the base
 * path and nothing else.
 */
function githubPagesArtifacts({ base }) {
  return {
    name: 'kalapriti-gh-pages-artifacts',
    apply: 'build',
    // closeBundle runs after publicDir has been copied, so this always wins.
    // Skipped for the SSR build, which writes to dist-server/, not dist/.
    closeBundle() {
      if (this.environment?.config?.build?.ssr) return
      // closeBundle also runs when the build has failed. Without this guard
      // the write throws ENOENT on the missing dist/ and that is the error the
      // build reports — hiding the syntax error that actually caused it.
      const dist = resolve(import.meta.dirname, 'dist')
      if (!existsSync(dist)) return
      writeFileSync(resolve(dist, '404.html'), ghPagesSpaFallback(base))
    },
  }
}

export default defineConfig({
  base: BASE,
  plugins: [react(), githubPagesArtifacts({ base: BASE })],
})
