import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * TWO ENVIRONMENTS, ONE CODEBASE
 *
 *   dev  branch -> staging    -> GitHub Pages at /kalapriti/   (VITE_BASE=/kalapriti/)
 *   main branch -> production -> Hostinger at the domain apex  (VITE_BASE=/)
 *
 * The base is the only thing that differs, and CI injects it rather than it
 * being hardcoded — hardcoding it is what broke this site twice before.
 * Locally it defaults to "/", so `npm run dev` just works.
 *
 * Every asset URL comes from `asset()` in src/data/site.js, which reads
 * import.meta.env.BASE_URL. Vite rewrites the favicon and the hero preload in
 * index.html automatically, so nothing there needs touching either.
 */
const BASE = process.env.VITE_BASE || '/'
const IS_STAGING = process.env.VITE_ENV === 'staging'

/**
 * GitHub Pages has no server-side rewrites, so a deep link like
 * /kalapriti/services is answered with 404.html. That file encodes the path
 * into a query string and bounces to index.html, where a snippet restores the
 * real URL before React mounts.
 *
 * `pathSegmentsToKeep` must equal the number of segments in the base or the
 * redirect mangles the URL — deriving it here means it can never drift.
 *
 * Apache does real rewrites (see public/.htaccess), so production skips this
 * file entirely and answers deep links with a genuine HTTP 200.
 */
function ghPagesSpaFallback(base) {
  const segments = base.split('/').filter(Boolean).length
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Kalapriti Designs</title>
    <script>
      // GENERATED by vite.config.js for the staging (GitHub Pages) build.
      var pathSegmentsToKeep = ${segments}
      var l = window.location
      l.replace(
        l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
        l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
        l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
        (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
        l.hash
      )
    </script>
  </head>
  <body></body>
</html>
`
}

/**
 * Writes per-environment files after the bundle is on disk, so these always win
 * over anything copied verbatim from public/.
 */
function environmentArtifacts({ base, staging }) {
  return {
    name: 'kalapriti-environment-artifacts',
    apply: 'build',
    closeBundle() {
      const out = (name) => resolve(import.meta.dirname, 'dist', name)

      // Staging only: the Pages SPA shim.
      if (base !== '/') writeFileSync(out('404.html'), ghPagesSpaFallback(base))

      // Staging must never be indexed, or it competes with the real domain in
      // search results and splits the site's ranking.
      if (staging) writeFileSync(out('robots.txt'), 'User-agent: *\nDisallow: /\n')
    },
  }
}

export default defineConfig({
  base: BASE,
  plugins: [react(), environmentArtifacts({ base: BASE, staging: IS_STAGING })],
})
