"""
Responsive image pipeline.

    python scripts/images.py            # or: npm run images

Reads the PNG/JPG originals listed in PLAN from public/assets, writes AVIF and
WebP variants at each width into public/assets/img, and regenerates
src/data/images.js (which <Picture> reads for srcset + zero-CLS dimensions).

To add a real project photo: drop it in public/assets, add a PLAN entry, run
this, then reference it as <Picture name="…" />. The PNG stays as the <img>
fallback for browsers with neither format.

Requires Pillow with AVIF + WebP support (pip install pillow).
"""
import json, os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'public', 'assets')
OUT  = os.path.join(ROOT, 'public', 'assets', 'img')
MANIFEST_JS = os.path.join(ROOT, 'src', 'data', 'images.js')

# name -> (source file, crop to aspect (w, h) or None, output widths)
PLAN = {
    # Widths are what real photography should get. Anything above a source's
    # own width is skipped (see main), so these are a ceiling, not a promise.
    'hero':     ('hero.png',     None,   [640, 960, 1280, 1920]),
    'studio':   ('studio.png',   None,   [640, 960, 1280]),
    'project1': ('project1.png', (4, 3), [480, 960, 1440]),
    'project2': ('project2.png', (4, 3), [480, 960, 1440]),
    'project3': ('project3.png', (4, 3), [480, 960, 1440]),
    'project4': ('project4.png', (4, 3), [480, 960, 1440]),
}
AVIF = dict(quality=62)
WEBP = dict(quality=80, method=6)


def center_crop(im, aspect):
    aw, ah = aspect
    w, h = im.size
    th = int(w * ah / aw)
    if th <= h:
        top = (h - th) // 2
        return im.crop((0, top, w, top + th))
    tw = int(h * aw / ah)
    left = (w - tw) // 2
    return im.crop((left, 0, left + tw, h))


def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    for name, (src, aspect, widths) in PLAN.items():
        path = os.path.join(SRC, src)
        if not os.path.exists(path):
            print(f'  skip {name}: {src} not found', file=sys.stderr)
            continue
        im = Image.open(path).convert('RGB')
        if aspect:
            im = center_crop(im, aspect)
        w0, h0 = im.size

        # Never upscale. A width wider than the source is a bigger file with
        # no more detail in it — the old pipeline warned about this and then
        # did it anyway, so a phone downloaded a 94 kB "1280w" hero that was a
        # 640 px image stretched. Widths above the source are dropped, and the
        # source's own width stands in as the largest variant instead. PLAN
        # can keep asking for big widths; they appear once a big enough
        # original does.
        made = sorted({w for w in widths if w <= w0} | ({w0} if any(w > w0 for w in widths) else set()))
        skipped = [w for w in widths if w > w0]
        if skipped:
            print(f'  note {name}: {w0}px source, so not generating {skipped} (would be upscales)', file=sys.stderr)

        for w in made:
            r = im if w == w0 else im.resize((w, round(h0 * w / w0)), Image.LANCZOS)
            r.save(os.path.join(OUT, f'{name}-{w}.avif'), 'AVIF', **AVIF)
            r.save(os.path.join(OUT, f'{name}-{w}.webp'), 'WEBP', **WEBP)

        # Remove variants from earlier runs that this run did not produce,
        # or the old upscales keep shipping from public/ regardless.
        for f in os.listdir(OUT):
            stem, ext = os.path.splitext(f)
            if ext in ('.avif', '.webp') and stem.startswith(f'{name}-'):
                tail = stem[len(name) + 1:]
                if tail.isdigit() and int(tail) not in made:
                    os.remove(os.path.join(OUT, f))
                    print(f'  removed stale {f}')

        manifest[name] = dict(width=w0, height=h0, widths=made, fallback=f'assets/{src}')
        print(f'  {name:<9} {w0}x{h0}  widths={made}')

    lines = [
        '/**',
        ' * GENERATED by scripts/images.py — do not edit by hand.',
        ' * Intrinsic aspect (for zero-CLS width/height attrs) and the widths that',
        ' * exist on disk as .avif and .webp. PNG originals stay as the <img> fallback.',
        ' */',
        'export const IMAGES = {',
    ]
    for k, v in manifest.items():
        lines.append(f"  {k}: {{ width: {v['width']}, height: {v['height']}, widths: {v['widths']}, fallback: '{v['fallback']}' }},")
    lines.append('}')
    with open(MANIFEST_JS, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'  wrote {os.path.relpath(MANIFEST_JS, ROOT)}')


if __name__ == '__main__':
    main()
