"""
Responsive image pipeline.

    python scripts/images.py            # or: npm run images

Reads the PNG/JPG originals listed in PLAN from public/assets, writes AVIF and
WebP variants at each width into public/assets/img, and regenerates
src/data/images.js (which <Picture> reads for srcset + zero-CLS dimensions).

To add a real project photo: drop it in public/assets, add a PLAN entry, run
this, then reference it as <Picture name="…" />. The PNG stays as the <img>
fallback for browsers with neither format.

Requires Pillow with AVIF + WebP support (pip install pillow).
"""
import json, os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'public', 'assets')
OUT  = os.path.join(ROOT, 'public', 'assets', 'img')
MANIFEST_JS = os.path.join(ROOT, 'src', 'data', 'images.js')

# name -> (source file, crop to aspect (w, h) or None, output widths)
PLAN = {
    'hero':     ('hero.png',     None,   [640, 1280]),
    'studio':   ('studio.png',   None,   [640, 960]),
    'project1': ('project1.png', (4, 3), [480, 960]),
    'project2': ('project2.png', (4, 3), [480, 960]),
    'project3': ('project3.png', (4, 3), [480, 960]),
    'project4': ('project4.png', (4, 3), [480, 960]),
}
AVIF = dict(quality=62)
WEBP = dict(quality=80, method=6)


def center_crop(im, aspect):
    aw, ah = aspect
    w, h = im.size
    th = int(w * ah / aw)
    if th <= h:
        top = (h - th) // 2
        return im.crop((0, top, w, top + th))
    tw = int(h * aw / ah)
    left = (w - tw) // 2
    return im.crop((left, 0, left + tw, h))


def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    for name, (src, aspect, widths) in PLAN.items():
        path = os.path.join(SRC, src)
        if not os.path.exists(path):
            print(f'  skip {name}: {src} not found', file=sys.stderr)
            continue
        im = Image.open(path).convert('RGB')
        if aspect:
            im = center_crop(im, aspect)
        w0, h0 = im.size
        for w in widths:
            if w > w0:
                print(f'  note {name}: {w}w is an upscale of a {w0}px source', file=sys.stderr)
            r = im.resize((w, round(h0 * w / w0)), Image.LANCZOS)
            r.save(os.path.join(OUT, f'{name}-{w}.avif'), 'AVIF', **AVIF)
            r.save(os.path.join(OUT, f'{name}-{w}.webp'), 'WEBP', **WEBP)
        manifest[name] = dict(width=w0, height=h0, widths=widths, fallback=f'assets/{src}')
        print(f'  {name:<9} {w0}x{h0}  widths={widths}')

    lines = [
        '/**',
        ' * GENERATED by scripts/images.py — do not edit by hand.',
        ' * Intrinsic aspect (for zero-CLS width/height attrs) and the widths that',
        ' * exist on disk as .avif and .webp. PNG originals stay as the <img> fallback.',
        ' */',
        'export const IMAGES = {',
    ]
    for k, v in manifest.items():
        lines.append(f"  {k}: {{ width: {v['width']}, height: {v['height']}, widths: {v['widths']}, fallback: '{v['fallback']}' }},")
    lines.append('}')
    with open(MANIFEST_JS, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'  wrote {os.path.relpath(MANIFEST_JS, ROOT)}')


if __name__ == '__main__':
    main()
